# Generated by Django 4.0.6 on 2022-07-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_list_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.AddField(
            model_name='list',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
