# Generated by Django 4.0.6 on 2022-07-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_list_description_list_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='importance',
        ),
        migrations.AlterField(
            model_name='list',
            name='duration',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
