# Generated by Django 4.0.6 on 2022-07-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_list_importance_alter_list_duration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Schedule',
        ),
    ]
